#include<stdio.h>
int main(int argc, char const *argv[])
{
    int a,b,c;
    a=123;
    while(a)  //multiple program are generated by this while loop g
    {
        b=a%10;
        c=c+1;
        a=a/10;
    }
    printf("%d",c);
}
